# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: 3 * x, a))

[3, 6, 9]

In [4]:
b = np.array([1, 2, 3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [5]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array Shape

In [15]:
# Vector(1차원)
vector = np.array([1, 4, 5, 8])
vector.shape

(4,)

In [12]:
# Matrix(2차원)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [13]:
# Tensor(3차원 이상)
tensor = np.arange(1, 25).reshape(2, 3, 4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [17]:
# size는 원소의 개수를 의미
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [21]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1, 2, 3], dtype = np.float32)
a

array([1., 2., 3.], dtype=float32)

In [20]:
b = np.array([1, 2, 3], dtype = np.int16)
b

array([1, 2, 3], dtype=int16)

### Reshape

In [22]:
matrix.shape

(2, 3)

In [23]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [24]:
matrix.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# -1은 numpy가 알아서 맞춰줌(단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [26]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
matrix.reshape(3, -1).shape

(3, 2)

In [29]:
tensor.reshape(4, -1).shape

(4, 6)

In [39]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [35]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [33]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Flatten

In [47]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [37]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [44]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
matrix[0][1]

2

In [46]:
matrix[0, 1]

2

In [49]:
tensor[1,1,2]

19

### Slicing

In [51]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
# 5, 6, 9, 10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [54]:
# 5, 6, 7, 9, 10, 11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [57]:
# 1, 3, 9, 11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [58]:
# X는 앞에 3열, y는 마지막열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))