In [1]:
import numpy as np

## 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오
        10 20 30 40
        50 60 70 80

In [2]:
np.arange(1, 9).reshape(2, 4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 2. 다음과 같은 행렬이 있다.


    
        m = np.array([[0, 1, 2, 3, 4],
                    [5, 6, 7, 8, 9],
                    [10, 11, 12, 13 14]])

In [3]:
m = np.arange(15).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
# 1) 이 행렬에서 값 7을 인덱싱한다.
m[1, 2]

7

In [5]:
# 2) 이 행렬에서 값 14를 인덱싱한다.
m[2, 4], m[-1, -1]

(14, 14)

In [6]:
# 3) 이 행렬에서 배열 [6,7]을 슬라이싱한다.
m[1, 1:3]

array([6, 7])

In [7]:
# 4) 이 행렬에서 배열 [7, 12]을 슬라이싱한다.
m[1:, 2]

array([ 7, 12])

In [8]:
# 5) 이 행렬에서 배열 [[3, 4], [8, 9]]을 슬라이싱한다.
m[:2, 3:]

array([[3, 4],
       [8, 9]])

## 3. 2번의 행렬 m을 1차원 벡터 f로 변환한 후 다음의 문제를 푸시오.

In [9]:
f = m.flatten()

In [10]:
# 1) 이 배열에서 3의 배수를 찾아라.
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [11]:
# 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [12]:
# 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
f[np.logical_and(f % 3 ==0, f % 4 ==1)]

array([9])

## 4. 값을 직접 입력하지 말고 아래의 행렬을 만드시오.

        2, 1, 0, 0, 0
        3, 2, 1, 0, 0
        0, 3, 2, 1, 0
        0, 0, 3, 2, 1
        0, 0, 0, 3, 2

In [13]:
np.eye(5, 5, k = -1) * 3 + np.eye(5, 5) * 2 + np.eye(5, 5, k = 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [14]:
a = np.eye(5, 5, dtype = np.int64)
a = a * 2
b = np.eye(5, 5, k = 1, dtype = np.int64)
c = np.eye(5, 5, k = -1, dtype = np.int64)
c = c * 3
a + b + c

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

## 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고, 이 데이터에 대해 다음과 같은 값을 구하시오.

In [15]:
np.random.seed(2021)
m = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [16]:
# 5 - 1
np.max(m)

9.9724

In [17]:
# 5 - 2
np.sum(m, axis = 1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [18]:
# 5 - 3
np.max(m, axis = 1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [19]:
# 5 - 4
np.mean(m, axis = 0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [20]:
# 5 - 5
np.min(m, axis = 0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

In [ ]:
m = np.random.uniform(0, 10, 30).reshape(5, 6)
m

array([[3.57680185, 7.53564802, 5.1589753 , 5.42474965, 8.0163574 ,
        7.43703485],
       [1.06534801, 3.8197143 , 0.71863816, 0.39412839, 6.4394694 ,
        7.18546485],
       [2.45590949, 1.29063637, 1.32260449, 0.2124251 , 0.53072487,
        4.13673763],
       [3.75117368, 9.76341706, 5.37353995, 6.03704677, 0.86509967,
        1.25881195],
       [7.84823821, 0.57516273, 5.90785676, 9.34754267, 9.08920028,
        4.2895815 ]])

In [ ]:
# 1) 전체의 최댓값
n = np.argmax(m)
row, col = n // 5 , n % 6
m[row, col] 

9.763417059035845

In [ ]:
# 2) 각 행의 합
m.sum(axis = 1)

array([37.14956707, 19.6227631 ,  9.94903795, 27.04908907, 37.05758214])

In [ ]:
# 3) 각 행의 최댓값
n = np.max(m, axis = 1)
n

array([8.0163574 , 7.18546485, 4.13673763, 9.76341706, 9.34754267])

In [ ]:
# 4) 각 열의 평균
m.mean(axis = 0)

array([3.73949425, 4.59691569, 3.69632293, 4.28317851, 4.98817032,
       4.86152615])

In [ ]:
# 5) 각 열의 최솟값
n = np.min(m, axis = 0)
n

array([1.06534801, 0.57516273, 0.71863816, 0.2124251 , 0.53072487,
       1.25881195])

## 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
        array([[1, 2, 3, 4],
            [46, 99, 100, 71],
            [81, 59, 90, 100]])

In [21]:
score = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [22]:
np.sort(score)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [23]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [24]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [25]:
# 행 전체를(:), 열 기준으로(s[::-1]) 재정렬
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [26]:
# 한 번에 작성
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

## 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [27]:
np.random.seed(2021)
dice = np.random.randint(1, 7, 100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [28]:
np.mean(dice)

3.7

In [29]:
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

## 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고, 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [30]:
# 일단 10개만 test
np.random.seed(2021)
price = 10000
rate = np.random.normal(0, 0.01, 10)
for i in range(10):
    price = price + np.round(price * rate[i])
    print(price, end = ', ')

10149.0, 10218.0, 10175.0, 10093.0, 10149.0, 10077.0, 10191.0, 10257.0, 10268.0, 10311.0, 

In [31]:
np.random.seed(2021)
price_list = []
rate = np.random.normal(0, 0.01, 250)
price = 10000
for i in range(250):
    price += np.round(price * rate[i])
    price_list.append(int(price))

In [32]:
price_list[:10]

[10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257, 10268, 10311]