# Bag of Words

## Count Vectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you.']

In [2]:
cvector = CountVectorizer()

In [3]:
cvector.fit(corpus)         # 학습
cvector.transform(corpus).toarray()   # 변환

array([[1, 1, 2, 1, 2, 1]])

In [4]:
cvector.vocabulary_

{'because': 0, 'know': 1, 'love': 2, 'want': 3, 'you': 4, 'your': 5}

In [5]:
output = cvector.fit_transform(corpus).toarray()
output

array([[1, 1, 2, 1, 2, 1]])

In [6]:
output.shape

(1, 6)

- 불용어를 제거한 BoW

In [7]:
# 사용자 정의
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [8]:
# Scikit-Learn 제공
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [9]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
# NLTK 제공
from nltk.corpus import stopwords

text=["Family is not an important thing. It's everything."]
sw = stopwords.words("english")
vect = CountVectorizer(stop_words =sw)
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [11]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key

In [12]:
get_word(2, vect.vocabulary_)

'important'

- N-gram

In [13]:
text1 = ['Machine learning is fun and not boring.']
text2 = ['Machine is boring and learning is not fun.']

In [14]:
vect = CountVectorizer()
print(vect.fit_transform(text1).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'machine': 5, 'learning': 4, 'is': 3, 'fun': 2, 'and': 0, 'not': 6, 'boring': 1}


In [15]:
print(vect.fit_transform(text2).toarray())
print(vect.vocabulary_)

[[1 1 1 2 1 1 1]]
{'machine': 5, 'is': 3, 'boring': 1, 'and': 0, 'learning': 4, 'not': 6, 'fun': 2}


In [16]:
# N-gram range:(1, 2)
vect = CountVectorizer(ngram_range=(1,2))
print(vect.fit_transform(text1).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]]
{'machine': 9, 'learning': 7, 'is': 5, 'fun': 3, 'and': 0, 'not': 11, 'boring': 2, 'machine learning': 10, 'learning is': 8, 'is fun': 6, 'fun and': 4, 'and not': 1, 'not boring': 12}


In [17]:
print(vect.fit_transform(text2).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1 2 1 1 1 1 1 1 1 1]]
{'machine': 10, 'is': 5, 'boring': 2, 'and': 0, 'learning': 8, 'not': 12, 'fun': 4, 'machine is': 11, 'is boring': 6, 'boring and': 3, 'and learning': 1, 'learning is': 9, 'is not': 7, 'not fun': 13}


In [18]:
# N-gram range:(1, 3)
vect = CountVectorizer(ngram_range=(1,3), stop_words='english')
print(vect.fit_transform(text1).toarray())
print(vect.vocabulary_)

[[1 1 1 1 1 1 1 1 1]]
{'machine': 6, 'learning': 3, 'fun': 1, 'boring': 0, 'machine learning': 7, 'learning fun': 4, 'fun boring': 2, 'machine learning fun': 8, 'learning fun boring': 5}


- Hyper Parameter

In [19]:
vect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

- DTM

In [20]:
corpus = [
          "you know I want your love",
          "I like you",
          "what shoud I do"
]
vect = CountVectorizer()
print(vect.fit_transform(corpus).toarray())
print(vect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'shoud': 4, 'do': 0}


## TF-IDF Vectorizer

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray().round(2))
print(tvect.vocabulary_)

[[0.   0.47 0.   0.47 0.   0.47 0.   0.36 0.47]
 [0.   0.   0.8  0.   0.   0.   0.   0.61 0.  ]
 [0.58 0.   0.   0.   0.58 0.   0.58 0.   0.  ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'shoud': 4, 'do': 0}


In [22]:
tvect = TfidfVectorizer(ngram_range=(1,2), stop_words='english')
print(tvect.fit_transform(corpus).toarray().round(2))
print(tvect.vocabulary_)

[[0.45 0.45 0.   0.45 0.   0.45 0.45]
 [0.   0.   1.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   1.   0.   0.  ]]
{'know': 0, 'want': 5, 'love': 3, 'know want': 1, 'want love': 6, 'like': 2, 'shoud': 4}


In [23]:
tvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 2),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}